# MJSRecon Default Configuration
# This file contains default configuration values for all modules

# Global Tools Configuration
tools:
  required:
    - "waybackurls"
    - "gau"
    - "katana"
    - "httpx"
    - "unfurl"
    - "fallparams"
    - "gf"
  full_mode:
    - "jsluice"
    - "trufflehog"
  python_tools:
    secretfinder: "src/tools/secretfinder.py"
    linkfinder: "src/tools/linkfinder.py"

# Proxy Configuration
proxy:
  enabled: false
  url: null
  auth: null
  no_proxy: null
  timeout: 30
  verify_ssl: false



# Timeouts for various operations
timeouts:
  command: 1200  # 20 minutes for long-running tools
  discovery: 600  # 10 minutes for discovery tools (gau, waybackurls, katana)
  download: 120
  analysis: 300  # Increased for potentially large JS files
  verify: 10     # Timeout for a single URL verification request

# Discovery Module Configuration
discovery:
  gather_mode: "gwk"  # g=gau, w=wayback, k=katana
  depth: 2
  use_uro: false

# Global URL filtering configuration
excluded_extensions:
  - ".css"
  - ".png"
  - ".jpg"
  - ".jpeg"
  - ".svg"
  - ".ico"
  - ".gif"
  - ".woff"
  - ".woff2"
  - ".swf"
  - ".map"

# Validation Module Configuration
validation:
  max_workers: 20  # Reduced from 50 to prevent high CPU usage
  timeout: 30
  verify_ssl: false

# Processing Module Configuration
processing:
  max_file_size_mb: 10
  download_timeout: 30
  max_concurrent_downloads: 10

# Download Module Configuration
download:
  max_file_size_mb: 10
  timeout: 30
  max_concurrent: 20
  allowed_extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
    - ".vue"
    - ".json"

# Analysis Module Configuration
analysis:
  max_workers: 8  # Analysis is CPU-bound, fewer workers are better
  max_file_size_mb: 10

# Enumeration / Fuzzing Configuration
enumeration:
  fuzz_threads: 40
  fuzz_timeout: 10
  # Fuzzing wordlist generation settings
  prefixes:
    - "app"
    - "lib"
    - "vendor"
    - "dist"
    - "src"
    - "core"
    - "main"
  suffixes:
    - "bundle"
    - "min"
    - "dev"
    - "prod"
    - "v1"
    - "v2"
  separators:
    - ""
    - "-"
    - "_"
    - "."

# FuzzingJS Module Configuration (alias for enumeration)
fuzzingjs:
  fuzz_threads: 40
  fuzz_timeout: 10
  # Fuzzing path selection behavior
  js_only_paths: true  # Only fuzz paths from JavaScript files (recommended)
  include_related_paths: false  # Include paths from related file types (.ts, .jsx, .vue)
  max_paths: 50  # Maximum number of paths to fuzz

# Parameter Extraction Configuration
param_passive:
  important_extensions:
    - ".php"
    - ".asp"
    - ".aspx"
    - ".jsp"
    - ".jspx"
    - ".ashx"
    - ".phpx"
    - ".html"
    - ".htm"
    - ".js"
    - ".json"
    - ".map"
  max_workers: 20

# Parameter Enumeration Configuration
fallparams:
  threads: 5
  max_workers: 20

# SQL Injection Configuration
sqli:
  scanner: "sqlmap"  # sqlmap, ghauri
  full_scan: false
  manual_blind: true
  header_test: false
  xor_test: false
  timeout: 15
  delay_threshold: 7
  max_workers: 10
  sqlmap_args: "--batch --random-agent --tamper=space2comment --level=5 --risk=3 --drop-set-cookie --threads 10 --dbs"
  ghauri_args: "--batch --dbs --level 3 --confirm"
  # Vulnerable file extensions that commonly have SQLi vulnerabilities
  vulnerable_extensions:
    - ".php"
    - ".asp"
    - ".aspx"
    - ".jsp"
    - ".jspx"
    - ".do"
    - ".action"
  # Common vulnerable file patterns
  vulnerable_files:
    - "product.php"
    - "view.php"
    - "show.php"
    - "display.php"
    - "detail.php"
    - "article.php"
    - "news.php"
    - "item.php"
    - "user.php"
    - "member.php"
    - "profile.php"
    - "account.php"
    - "search.php"
    - "query.php"
    - "result.php"
    - "list.php"
    - "category.php"
    - "page.php"
    - "index.php"
    - "main.php"
    - "product.asp"
    - "view.asp"
    - "show.asp"
    - "detail.asp"
    - "article.asp"
    - "news.asp"
    - "item.asp"
    - "user.asp"
    - "member.asp"
    - "profile.asp"
    - "account.asp"
    - "search.asp"
    - "query.asp"
    - "result.asp"
    - "list.asp"
    - "category.asp"
    - "page.asp"
    - "index.asp"
    - "main.asp"
  # SQL injection indicators in URLs
  sql_indicators:
    - "select"
    - "union"
    - "insert"
    - "update"
    - "delete"
    - "drop"
    - "create"
    - "alter"
    - "exec"
    - "execute"
    - "script"
    - "javascript"
    - "vbscript" 

# Performance Configuration
performance:
  max_concurrent_downloads: 20
  max_concurrent_analysis: 5
  max_concurrent_github_requests: 3
  cache_enabled: true
  cache_ttl: 3600  # 1 hour
  timeout_multiplier: 1.5  # Increase timeouts for slower connections

# Secret Patterns for Custom Scanning (used by all scanners)
secret_patterns:
  api_keys:
    - 'api_key.*[0-9a-zA-Z]{32,45}'
    - 'api_token.*[0-9a-zA-Z]{32,45}'
    - 'secret.*[0-9a-zA-Z]{32,45}'
  aws_keys:
    - 'AKIA[0-9A-Z]{16}'
    - 'aws_access_key_id.*[0-9A-Z]{20}'
    - 'aws_secret_access_key.*[0-9A-Za-z/+=]{40}'
  google_keys:
    - 'AIza[0-9A-Za-z\-_]{35}'
    - 'ya29\.[0-9A-Za-z\-_]+'
  database_connections:
    - 'mysql://[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+:[0-9]+/[a-zA-Z0-9._-]+'
    - 'postgresql://[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+:[0-9]+/[a-zA-Z0-9._-]+'
    - 'mongodb://[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+:[0-9]+/[a-zA-Z0-9._-]+'
  private_keys:
    - '-----BEGIN PRIVATE KEY-----'
    - '-----BEGIN RSA PRIVATE KEY-----'
    - '-----BEGIN DSA PRIVATE KEY-----'
    - '-----BEGIN EC PRIVATE KEY-----'
  passwords:
    - 'password.*[^\s]{8,}'
    - 'pwd.*[^\s]{8,}'

# Results directories for analysis tools
results_dirs:
  - "jsluice"
  - "secretfinder"
  - "linkfinder"
  - "trufflehog"

# Files used across modules
files:
  live_js: "live_js_urls.txt"
  deduplicated_js: "deduplicated_js_urls.txt"
  all_urls: "all_urls.txt"
  uro_urls: "uro_urls.txt"
  fuzzing_all: "js_urls_fuzzing_all.txt"
  fuzzing_new: "js_urls_fuzzing_new.txt"
  permutation_wordlist: "permutation_wordlist.txt"
  sqli_targets: "sqli_targets.txt"
  waybackurls_urls: "waybackurls_urls.txt"
  waybackurls_filtered: "waybackurls_filtered_urls.txt"
  wayback_urls: "wayback_urls.txt"
  wayback_filtered: "wayback_filtered_urls.txt"
  gau_urls: "gau_urls.txt"
  gau_filtered: "gau_filtered_urls.txt"
  katana_urls: "katana_urls.txt"
  katana_filtered: "katana_filtered_urls.txt"
  # Code hosting scanner files
  github_repositories: "repositories.json"
  github_secrets: "secrets_found.json"
  github_useful_data: "useful_data.json"
  github_organizations: "organizations.json"
  github_users: "users.json"
  github_report: "github_recon_report.md"
  gitlab_repositories: "repositories.json"
  gitlab_secrets: "secrets.json"
  gitlab_useful_data: "useful_data.json"
  bitbucket_repositories: "repositories.json"
  bitbucket_secrets: "secrets.json"
  bitbucket_useful_data: "useful_data.json"
  gitea_repositories: "repositories.json"
  gitea_secrets: "secrets.json"
  gitea_useful_data: "useful_data.json"
  sqli_results: "sqli_results.txt"
  sqli_manual_results: "sqli_manual_results.txt"
  sqli_header_results: "sqli_header_results.txt"
  sqli_xor_results: "sqli_xor_results.txt"

# Additional Directories
dirs:
  downloaded_files: "downloaded_files"
  results: "results"
  ffuf_results: "ffuf_results"
  sqli_results: "sqli_results"
  param_passive: "param_passive"
  fallparams_results: "fallparams_results"
  jsluice: "jsluice"
  secretfinder: "secretfinder"
  linkfinder: "linkfinder"
  trufflehog: "trufflehog"

# Scanner configurations are defined in separate files:
# - config/github_scanner.yaml
# - config/gitlab_scanner.yaml  
# - config/bitbucket_scanner.yaml
# - config/gitea_scanner.yaml

# Reporting Configuration
reporting:
  generate_html: true
  generate_json: true
  generate_markdown: true
  include_timestamps: true 